---

- name: Create VMs in the private network
  hosts: all
  gather_facts: false
  tasks:
    - name: Create VM
      ansible.builtin.include_role:
        name: "{{ 'dynamic-private-vm' if (dynamic_provisioning | default(false)) else 'private-vm' }}"
